# Example configuration file for rustnapshot

# Snapshots directory
dest_dir = "/mnt/defvol/_snapshots/"
# Directory to be snapshoted
source_dir = "/mnt/defvol/_active/root/"
# SQLite database file PATH, created if no exists, recommended to be in the snapshots dir
database_file = "/mnt/defvol/_snapshots/rustnapshot.sqlite"
# Prefix for the snapshots, they will be saved in the format prefix-$current_date
snapshot_prefix = "root"
# Last snapshots to keep. If prefix is specified then only the snapshots with that prefix
# are deleted
keep_only = "2"
